[env:esp-wrover-kit]
platform = espressif32
board = esp-wrover-kit
framework = arduino
monitor_speed = 115200

; This tells the board to use its extra WROVER memory!
build_flags =
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue

; Your standard libraries
lib_deps =
    miguelbalboa/MFRC522 @ ^1.4.11
    marcoschwartz/LiquidCrystal_I2C @ ^1.1.4
    madhephaestus/ESP32Servo @ ^3.1.3