[env:esp32cam]
; Using platform 6.x which has better face recognition support with modern APIs
platform = espressif32@6.5.0
board = esp32cam
framework = arduino
monitor_speed = 115200

# Configuration de la mémoire (CRITIQUE pour l'IA)
# On utilise huge_app car le code de reconnaissance faciale est très volumineux
board_build.partitions = huge_app.csv

build_flags = 
    -D BOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -D _DISABLE_TLS_
    -D THINGER_EXTERNAL_CERTIFICATE
    -D CONFIG_ESP_FACE_DETECT_ENABLED=1
    -D CONFIG_ESP_FACE_RECOGNITION_ENABLED=1

lib_deps = 
    thinger.io
    bblanchon/ArduinoJson @ ^6.21.3
    witnessmenow/UniversalTelegramBot
    ; On garde uniquement la caméra officielle
    https://github.com/espressif/esp32-camera.git
     
