[env:esp32cam]
platform = espressif32
board = esp32cam
framework = arduino

; Vitesse du terminal série (doit correspondre à ton Serial.begin)
monitor_speed = 115200

; Activation de la PSRAM (Indispensable pour l'ESP32-CAM)
build_flags = 
	-D BOARD_HAS_PSRAM
	-mfix-esp32-psram-cache-issue
    -D DISABLE_TLS
    -D THINGER_SERIAL_DEBUG
; Installation automatique des bibliothèques
lib_deps = 
    thinger-io/thinger.io
    